import { existsSync, readFileSync, writeFileSync } from "fs";
import { spawn, spawnSync } from "child_process";
import net from "net";
import path from "path";

const port = Number.parseInt(process.env.PORT || "60000", 10);
const cwd = process.cwd();
const tunnelEnvPath = path.join(cwd, ".env.tunnel");
const cloudflaredExeCandidates = [
  "cloudflared",
  "cloudflared.exe",
  path.join(process.env.LOCALAPPDATA || "", "Microsoft", "WinGet", "Packages", "Cloudflare.cloudflared_Microsoft.Winget.Source_8wekyb3d8bbwe", "cloudflared.exe"),
].filter(Boolean);

function canConnect(targetPort: number) {
  return new Promise<boolean>((resolve) => {
    const socket = net.createConnection({ host: "127.0.0.1", port: targetPort });
    socket.once("connect", () => {
      socket.destroy();
      resolve(true);
    });
    socket.once("error", () => resolve(false));
  });
}

function resolveCloudflaredPath() {
  for (const candidate of cloudflaredExeCandidates) {
    if (candidate.endsWith(".exe") && existsSync(candidate)) return candidate;
    const command = process.platform === "win32" ? `where.exe ${candidate}` : `which ${candidate}`;
    const result = spawnSync(command, {
      shell: true,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    const firstLine = result.stdout?.split(/\r?\n/).map((line) => line.trim()).find(Boolean);
    if (firstLine && existsSync(firstLine)) return firstLine;
  }
  return "";
}

function normalizeUrl(url: string) {
  return url.endsWith("/") ? url : `${url}/`;
}

function writeTunnelEnv(url: string) {
  const normalizedUrl = normalizeUrl(url);
  const content = [
    "# Auto-generated by `npm run tunnel`.",
    "# This file is loaded after .env.local so the latest quick tunnel can override OSSURL.",
    `OSSURL=${normalizedUrl}`,
    "",
  ].join("\n");
  writeFileSync(tunnelEnvPath, content, "utf8");
  console.log(`[tunnel] wrote ${tunnelEnvPath}`);
  console.log(`[tunnel] OSSURL=${normalizedUrl}`);
}

function printExistingTunnelEnv() {
  if (!existsSync(tunnelEnvPath)) return;
  const content = readFileSync(tunnelEnvPath, "utf8");
  const match = content.match(/^\s*OSSURL=(.+)\s*$/m);
  if (match?.[1]) {
    console.log(`[tunnel] current ${match[1].trim()}`);
  }
}

async function main() {
  const reachable = await canConnect(port);
  if (!reachable) {
    console.error(`[tunnel] local server http://127.0.0.1:${port} is not reachable. Start the app before opening the tunnel.`);
    process.exit(1);
  }

  const cloudflaredPath = resolveCloudflaredPath();
  if (!cloudflaredPath) {
    console.error("[tunnel] cloudflared was not found. Install it first, for example with `winget install --id Cloudflare.cloudflared -e`.");
    process.exit(1);
  }

  printExistingTunnelEnv();

  const child = spawn(cloudflaredPath, ["tunnel", "--url", `http://127.0.0.1:${port}`], {
    cwd,
    env: process.env,
    stdio: ["ignore", "pipe", "pipe"],
  });

  let wroteUrl = false;
  const handleOutput = (chunk: Buffer) => {
    const text = chunk.toString("utf8");
    process.stdout.write(text);
    const match = text.match(/https:\/\/[-a-z0-9]+\.trycloudflare\.com/ig);
    const latestUrl = match?.[match.length - 1];
    if (latestUrl) {
      writeTunnelEnv(latestUrl);
      wroteUrl = true;
    }
  };

  child.stdout.on("data", handleOutput);
  child.stderr.on("data", handleOutput);

  child.on("exit", (code) => {
    if (!wroteUrl) {
      console.error("[tunnel] no public URL was detected. `.env.tunnel` was not updated.");
    }
    process.exit(code ?? 0);
  });

  process.on("SIGINT", () => child.kill("SIGINT"));
  process.on("SIGTERM", () => child.kill("SIGTERM"));
}

void main();
